<?php

/**
 * @file
 *
 * Provide a pdf format for printing the statistics displayed on node Statistics page. 
 */

/**
 * Implements hook_libraries_info().
 * 
 * @see xautoload.api.php
 */
function simpleads_statsprint_libraries_info() {
  return array(
    'dompdf' => array(
      'name' => 'dompdf/dompdf',
      'xautoload' => function($adaptor) {
        /** @var \Drupal\xautoload\Adapter\LocalDirectoryAdapter $adapter */
        // Scans sites/all/libraries/dompdf/composer.json to look for
        // autoloader information.
        $adaptor->composerJson('composer.json');
      }
    ),
  );
}

/**
 * Implements hook_permission().
 */
function simpleads_statsprint_permission() {
  return array(
    'access simpleads statsprint' => array(
      'title' => t('Access the pdf stats page.'),
      'description' => t('Allow view of SimpleAds statitics in pdf format.')
    ),
  );
}
