<?php

/**
 * @file
 *
 * Provide a pdf format for printing the statistics displayed on node Statistics page. 
 */

/**
 * Implements hook_libraries_info().
 * 
 * @see xautoload.api.php
 */
function simpleads_statsprint_libraries_info() {
  return array(
    'dompdf' => array(
      'name' => 'dompdf/dompdf',
      'xautoload' => function($adaptor) {
        /** @var \Drupal\xautoload\Adapter\LocalDirectoryAdapter $adapter */
        // Scans sites/all/libraries/dompdf/composer.json to look for
        // autoloader information.
        $adaptor->composerJson('composer.json');
      }
    ),
  );
}

/**
 * Implements hook_permission().
 */
function simpleads_statsprint_permission() {
  return array(
    'access simpleads statsprint' => array(
      'title' => t('Access the pdf stats page.'),
      'description' => t('Allow view of SimpleAds statitics in pdf format.')
    ),
  );
}

/**
 * Implements hook_menu().
 */
function simpleads_statsprint_menu() {
 return array(
   'printadstat/%' => array(
     'page callback' => 'simpleads_statsprint_pdf',
     'page arguments' => array(1),
     'access arguments' => array('access simpleads statsprint'),
     'type' => MENU_CALLBACK,
     'file' => 'print.ad.stat.inc',
     'file path' => drupal_get_path('module', 'simpleads_statsprint'),
   ),
 );
}

/**
 * Implements hook_preprocess_page().
 */
function simpleads_statsprint_preprocess_page(&$variables) {
  if (arg(2) == 'stats' || arg(2) == 'stat') {
    unset($_SESSION['simpleads_statsprint']);
    $_SESSION['simpleads_statsprint'] = array(
      'markup' => $variables['page']['content']['system_main']['main']['#markup'],
      'nid' => arg(1),
    );
    $markup = '<p><a href="' . $variables['base_path'];
    $markup .= 'printadstat/' . arg(1);
    $markup .= '" target=_blank>Generate PDF</a></p>';
    $markup .= $variables['page']['content']['system_main']['main']['#markup'];
    $variables['page']['content']['system_main']['main']['#markup'] = $markup;
  }

}

/**
 * Implemnts hook_theme().
 */
function simpleads_statsprint_theme() {
  return array(
    'simpleads_statsprint' => array(
      'variables' => array(
        'total' => array(),
        'data' => array(),
      ),
      'template' => 'simpleads-statsprint',
    ),
  );
}